language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - moataz.mohammady@gmai.com
      - moataz@wuilt.com
    on_success: always
    on_failure: always
node_js:
  - '12.13.1'
git:
  depth: 3
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - npm run build
after_success:
  - "npm run deploy"
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  tracking-id: $TRACKING_ID
  local_dir: public
  on:
    branch: develop
