language: node_js
node_js:
  - '10'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  tracking-id: $TRACKING_ID
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop
before_script:
  - 'rm -rf node_modules'
  - 'rm -rf package-lock.json'
  - 'npm i -g gatsby'
  - 'npm i'
script:
  - 'npm run test'
after_success:
  - 'npm run deploy'
